apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-aula-14-05
  labels:
    aula: 14-05
spec:
  replicas: 3
  selector:
    matchLabels:
      aula: 14-05
  template:
    metadata:
      labels:
        aula: 14-05
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80